language: ruby
before_install:
  - gem install bundler -v '< 2'
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0
script: "bundle exec rake test"
notifications:
  email:
    - michael+geokit@noack.com.au
sudo: false
cache: bundler
